/* Definitions for unrandom artefacts. */

/**********************************************************************
 * WARNING!
 *
 * This file is automatically generated. Do not edit this file directly;
 * instead edit art-data.txt to modify unrandart data, or util/art-data.pl
 * if this file is not being generated to your taste.
 *
 * If the unrandart_entry struct is changed or a new artefact property is
 * added to artefact_prop_type, then change art-data.pl so that the
 * art-data.h file it produces matches up with the new structure.
 *
 * Ignoring these warnings and editing this file directly will cause you
 * to be hunted down and eaten by dire tarantulas.
 **********************************************************************/

#ifndef art_data_h
#ifndef ART_FUNC_H
#error "art-func.h must be included before art-data.h"
#endif

#define art_data_h

/* UNRAND_DUMMY1 */
{
    "DUMMY UNRANDART 1", "DUMMY UNRANDART 1", NULL, NULL, 
    OBJ_UNASSIGNED, 250, 250, 0, BLACK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SINGING_SWORD */
{
    "Singing Sword", "Singing Sword", NULL, NULL, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, +7, 0, ETC_GOLD, 1200, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _SINGING_SWORD_equip, _SINGING_SWORD_unequip, _SINGING_SWORD_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_TROG */
{
    "Wrath of Trog", "Wrath of Trog", NULL, NULL, 
    OBJ_WEAPONS, WPN_BATTLEAXE, +8, 0, ETC_BLOOD, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ANTIMAGIC, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 50, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _TROG_equip, _TROG_unequip, NULL, NULL, NULL, NULL, 
},

/* UNRAND_VARIABILITY */
{
    "Mace of Variability", "Mace of Variability", NULL, NULL, 
    OBJ_WEAPONS, WPN_GREAT_MACE, +0, 0, ETC_RANDOM, 700, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_CHAOS, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    NULL, NULL, _VARIABILITY_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_PRUNE */
{
    "Glaive of Prune", "Glaive of Prune", NULL, NULL, 
    OBJ_WEAPONS, WPN_GLAIVE, +12, 0, LIGHTMAGENTA, 1000, 
    UNRAND_FLAG_CHAOTIC, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _PRUNE_equip, NULL, _PRUNE_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_POWER */
{
    "Sword of Power", "Sword of Power", NULL, NULL, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, +0, 0, RED, 1000, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    _POWER_equip, NULL, _POWER_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_OLGREB */
{
    "Staff of Olgreb", "Staff of Olgreb", NULL, NULL, 
    OBJ_WEAPONS, WPN_STAFF, +0, 0, ETC_POISON, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    _OLGREB_equip, _OLGREB_unequip, _OLGREB_world_reacts, _OLGREB_melee_effects, NULL, _OLGREB_evoke, 
},

/* UNRAND_WUCAD_MU */
{
    "Staff of Wucad Mu", "Staff of Wucad Mu", NULL, "channel", 
    OBJ_WEAPONS, WPN_STAFF, +9, 0, ETC_MAGIC, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, _WUCAD_MU_evoke, 
},

/* UNRAND_VAMPIRES_TOOTH */
{
    "Vampire's Tooth", "Vampire's Tooth", NULL, NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +4, 0, ETC_BONE, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VAMPIRISM, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _VAMPIRES_TOOTH_equip, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_CURSES */
{
    "Scythe of Curses", "Scythe of Curses", NULL, NULL, 
    OBJ_WEAPONS, WPN_SCYTHE, +13, 0, ETC_DEATH, 800, 
    UNRAND_FLAG_EVIL, 
    {
        SPWPN_DRAINING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _CURSES_equip, NULL, _CURSES_world_reacts, _CURSES_melee_effects, NULL, NULL, 
},

/* UNRAND_TORMENT */
{
    "Sceptre of Torment", "Sceptre of Torment", NULL, NULL, 
    OBJ_WEAPONS, WPN_MACE, +7, 0, ETC_GOLD, 1200, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _TORMENT_equip, NULL, _TORMENT_world_reacts, _TORMENT_melee_effects, NULL, NULL, 
},

/* UNRAND_ZONGULDROK */
{
    "Sword of Zonguldrok", "Sword of Zonguldrok", NULL, NULL, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, +9, 0, ETC_BONE, 1250, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL | UNRAND_FLAG_CORPSE_VIOLATING, 
    {
        SPWPN_REAPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _ZONGULDROK_equip, NULL, _ZONGULDROK_world_reacts, _ZONGULDROK_melee_effects, NULL, NULL, 
},

/* UNRAND_CEREBOV */
{
    "Sword of Cerebov", "great serpentine sword", "flamberge", NULL, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, +6, 0, ETC_FIRE, 2000, 
    UNRAND_FLAG_UNHOLY | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, +1, +1, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _CEREBOV_melee_effects, NULL, NULL, 
},

/* UNRAND_DISPATER */
{
    "Staff of Dispater", "golden staff", NULL, NULL, 
    OBJ_WEAPONS, WPN_STAFF, +4, 0, ETC_GOLD, 1200, 
    UNRAND_FLAG_UNHOLY | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _DISPATER_melee_effects, NULL, _DISPATER_evoke, 
},

/* UNRAND_ASMODEUS */
{
    "Sceptre of Asmodeus", "ruby sceptre", NULL, NULL, 
    OBJ_WEAPONS, WPN_STAFF, +7, 0, ETC_BLOOD, 1500, 
    UNRAND_FLAG_UNHOLY | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _ASMODEUS_melee_effects, NULL, _ASMODEUS_evoke, 
},

/* UNRAND_FAERIE */
{
    "faerie dragon armour", "faerie dragon armour", NULL, NULL, 
    OBJ_ARMOUR, ARM_MOTTLED_DRAGON_ARMOUR, +3, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NOGEN | UNRAND_FLAG_UNIDED, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BLOODBANE */
{
    "demon blade \"Bloodbane\"", "demon blade \"Bloodbane\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_DEMON_BLADE, +8, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 9, 0, 
        0, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FLAMING_DEATH */
{
    "scimitar of Flaming Death", "scimitar of Flaming Death", NULL, NULL, 
    OBJ_WEAPONS, WPN_SCIMITAR, +6, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        2, -1, 0, 1, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _FLAMING_DEATH_equip, _FLAMING_DEATH_unequip, NULL, _FLAMING_DEATH_melee_effects, NULL, NULL, 
},

/* UNRAND_BRILLIANCE */
{
    "eveningstar \"Brilliance\"", "eveningstar \"Brilliance\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_EVENINGSTAR, +1, 0, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 5, 0, 0, 5, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _BRILLIANCE_equip, _BRILLIANCE_unequip, NULL, NULL, NULL, NULL, 
},

/* UNRAND_LEECH */
{
    "demon blade \"Leech\"", "demon blade \"Leech\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_DEMON_BLADE, +8, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VAMPIRISM, -2, -2, -2, -2, -2, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_CHILLY_DEATH */
{
    "dagger of Chilly Death", "dagger of Chilly Death", NULL, NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +9, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FREEZING, 0, 0, 0, 0, 0, 
        -1, 2, 0, 1, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _CHILLY_DEATH_equip, _CHILLY_DEATH_unequip, NULL, _CHILLY_DEATH_melee_effects, NULL, NULL, 
},

/* UNRAND_MORG */
{
    "dagger \"Morg\"", "dagger \"Morg\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +4, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PAIN, 0, 0, 0, 5, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FINISHER */
{
    "scythe \"Finisher\"", "scythe \"Finisher\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_SCYTHE, +5, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_PUNK */
{
    "greatsling \"Punk\"", "greatsling \"Punk\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_GREATSLING, +7, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FREEZING, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_KRISHNA */
{
    "bow of Krishna \"Sharnga\"", "bow of Krishna \"Sharnga\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_LONGBOW, +8, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 3, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SKULLCRUSHER */
{
    "giant club \"Skullcrusher\"", "giant club \"Skullcrusher\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_GIANT_CLUB, +3, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 7, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_GUARD */
{
    "glaive of the Guard", "glaive of the Guard", NULL, NULL, 
    OBJ_WEAPONS, WPN_GLAIVE, +8, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 5, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_JIHAD */
{
    "sword of Jihad", "sword of Jihad", NULL, NULL, 
    OBJ_WEAPONS, WPN_EUDEMON_BLADE, +10, 0, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 0, 3, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 
        0, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_HELLFIRE */
{
    "arbalest \"Hellfire\"", "arbalest \"Hellfire\"", NULL, "hellfire,", 
    OBJ_WEAPONS, WPN_ARBALEST, +6, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_UNHOLY, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        2, -1, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _HELLFIRE_equip, NULL, NULL, NULL, _HELLFIRE_launch, NULL, 
},

/* UNRAND_DOOM_KNIGHT */
{
    "sword of the Doom Knight", "sword of the Doom Knight", NULL, NULL, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, +13, 0, BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PAIN, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_EOS */
{
    "morningstar \"Eos\"", "morningstar \"Eos\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_MORNINGSTAR, +11, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BOTONO */
{
    "spear of the Botono", "spear of the Botono", NULL, "Hex", 
    OBJ_WEAPONS, WPN_SPEAR, +6, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_REAPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, -6, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_OCTOPUS_KING */
{
    "trident of the Octopus King", "trident of the Octopus King", NULL, NULL, 
    OBJ_WEAPONS, WPN_TRIDENT, +8, 0, ETC_WATER, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 1, 1, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _OCTOPUS_KING_equip, NULL, _OCTOPUS_KING_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_ARGA */
{
    "mithril axe \"Arga\"", "mithril axe \"Arga\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_BROAD_AXE, +8, 0, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 2, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_ELEMENTAL_STAFF */
{
    "Elemental Staff", "Elemental Staff", NULL, NULL, 
    OBJ_WEAPONS, WPN_STAFF, +3, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 5, 0, 0, 0, 0, 
        2, 2, 1, 0, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _ELEMENTAL_STAFF_melee_effects, NULL, NULL, 
},

/* UNRAND_SNIPER */
{
    "heavy crossbow \"Sniper\"", "heavy crossbow \"Sniper\"", "heavy crossbow", NULL, 
    OBJ_WEAPONS, WPN_TRIPLE_CROSSBOW, +15, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +4, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_PIERCER */
{
    "longbow \"Piercer\"", "longbow \"Piercer\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_LONGBOW, +7, 0, CYAN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PENETRATION, 0, -2, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BLOWGUN_ASSASSIN */
{
    "blowgun of the Assassin", "blowgun of the Assassin", NULL, "stab,", 
    OBJ_WEAPONS, WPN_BLOWGUN, +6, 0, ETC_DEATH, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 2, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_WYRMBANE */
{
    "lance \"Wyrmbane\"", "lance \"Wyrmbane\"", "lance", "slay drac,", 
    OBJ_WEAPONS, WPN_SPEAR, +8, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 5, 0, 0, 0, 0, 
        1, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +2, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    _WYRMBANE_equip, NULL, NULL, _WYRMBANE_melee_effects, NULL, NULL, 
},

/* UNRAND_SPRIGGANS_KNIFE */
{
    "Spriggan's Knife", "Spriggan's Knife", "knife", NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +7, 0, LIGHTCYAN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 4, 0, 0, 4, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_PLUTONIUM_SWORD */
{
    "plutonium sword", "plutonium sword", NULL, NULL, 
    OBJ_WEAPONS, WPN_TRIPLE_SWORD, +14, 0, ETC_MUTAGENIC, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _PLUTONIUM_SWORD_melee_effects, NULL, NULL, 
},

/* UNRAND_UNDEADHUNTER */
{
    "great mace \"Undeadhunter\"", "great mace \"Undeadhunter\"", NULL, "disrupt,", 
    OBJ_WEAPONS, WPN_GREAT_MACE, +7, 0, LIGHTGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _UNDEADHUNTER_melee_effects, NULL, NULL, 
},

/* UNRAND_SNAKEBITE */
{
    "whip \"Snakebite\"", "whip \"Snakebite\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_WHIP, +8, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _SNAKEBITE_melee_effects, NULL, NULL, 
},

/* UNRAND_ACCURACY */
{
    "knife of Accuracy", "knife of Accuracy", "knife", NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +27, 0, LIGHTCYAN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_CRYSTAL_SPEAR */
{
    "Lehudib's crystal spear", "Lehudib's crystal spear", NULL, NULL, 
    OBJ_WEAPONS, WPN_SPEAR, +6, 0, GREEN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_CAPTAIN */
{
    "captain's cutlass", "captain's cutlass", NULL, NULL, 
    OBJ_WEAPONS, WPN_CUTLASS, +5, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _CAPTAIN_melee_effects, NULL, NULL, 
},

/* UNRAND_STORM_BOW */
{
    "storm bow", "storm bow", NULL, NULL, 
    OBJ_WEAPONS, WPN_LONGBOW, +8, 0, BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, _STORM_BOW_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_IGNORANCE */
{
    "large shield of Ignorance", "large shield of Ignorance", NULL, NULL, 
    OBJ_ARMOUR, ARM_LARGE_SHIELD, +6, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 2, 2, 0, -6, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_AUGMENTATION */
{
    "robe of Augmentation", "robe of Augmentation", NULL, NULL, 
    OBJ_ARMOUR, ARM_ROBE, +4, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 4, 4, 4, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_THIEF */
{
    "cloak of the Thief", "cloak of the Thief", NULL, NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +2, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, -2, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BULLSEYE */
{
    "large shield \"Bullseye\"", "large shield \"Bullseye\"", NULL, NULL, 
    OBJ_ARMOUR, ARM_LARGE_SHIELD, +15, 0, RED, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, -5, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DYROVEPREVA */
{
    "crown of Dyrovepreva", "crown of Dyrovepreva", NULL, NULL, 
    OBJ_ARMOUR, ARM_HAT, +3, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 2, 0, 
        0, 0, 1, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BEAR_SPIRIT */
{
    "hat of the Bear Spirit", "hat of the Bear Spirit", NULL, NULL, 
    OBJ_ARMOUR, ARM_HAT, +2, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_SPIRIT_SHIELD, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 2, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_MISFORTUNE */
{
    "robe of Misfortune", "robe of Misfortune", NULL, NULL, 
    OBJ_ARMOUR, ARM_ROBE, -5, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_RANDAPP | UNRAND_FLAG_UNIDED, 
    {
        SPARM_NORMAL, 0, -4, -2, -2, -2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 1, 0, 0, 0, 
        1, 0, 0, 1, -2, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FLASH */
{
    "cloak of Flash", "cloak of Flash", NULL, NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +3, 0, ETC_FLASH, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BOOTS_ASSASSIN */
{
    "boots of the Assassin", "boots of the Assassin", NULL, NULL, 
    OBJ_ARMOUR, ARM_BOOTS, +2, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 2, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_LEAR */
{
    "Lear's hauberk", "Lear's hauberk", NULL, NULL, 
    OBJ_ARMOUR, ARM_CHAIN_MAIL, 27, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_ZHOR */
{
    "skin of Zhor", "skin of Zhor", NULL, NULL, 
    OBJ_ARMOUR, ARM_ANIMAL_SKIN, +4, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 3, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SALAMANDER */
{
    "salamander hide armour", "salamander hide armour", NULL, NULL, 
    OBJ_ARMOUR, ARM_LEATHER_ARMOUR, +3, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        2, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_WAR */
{
    "gauntlets of War", "gauntlets of War", NULL, NULL, 
    OBJ_ARMOUR, ARM_GLOVES, +3, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 5, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_RESISTANCE */
{
    "shield of Resistance", "shield of Resistance", NULL, NULL, 
    OBJ_ARMOUR, ARM_SHIELD, +2, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        1, 1, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FOLLY */
{
    "robe of Folly", "robe of Folly", NULL, NULL, 
    OBJ_ARMOUR, ARM_ROBE, 3, 0, LIGHTGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_ARCHMAGI, 0, 0, 0, 5, 0, 
        0, 0, 0, 0, 0, -2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_MAXWELL */
{
    "Maxwell's patent armour", "Maxwell's patent armour", NULL, NULL, 
    OBJ_ARMOUR, ARM_PLATE_ARMOUR, +15, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 
        0, 0, 0, -1, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DRAGONMASK */
{
    "mask of the Dragon", "mask of the Dragon", NULL, NULL, 
    OBJ_ARMOUR, ARM_HAT, 0, 0, ETC_SHIMMER_BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 3, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_NIGHT */
{
    "robe of Night", "robe of Night", NULL, NULL, 
    OBJ_ARMOUR, ARM_ROBE, +4, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        1, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _NIGHT_equip, _NIGHT_unequip, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DRAGON_KING */
{
    "armour of the Dragon King", "armour of the Dragon King", NULL, NULL, 
    OBJ_ARMOUR, ARM_GOLD_DRAGON_ARMOUR, +9, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_ALCHEMIST */
{
    "hat of the Alchemist", "hat of the Alchemist", NULL, NULL, 
    OBJ_ARMOUR, ARM_HAT, -2, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        1, 1, 1, 1, 1, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        1, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FENCERS_GLOVES */
{
    "fencer's gloves", "fencer's gloves", NULL, NULL, 
    OBJ_ARMOUR, ARM_GLOVES, +2, 0, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 3, 0, 0, 6, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 2, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_STARLIGHT */
{
    "cloak of Starlight", "cloak of Starlight", NULL, NULL, 
    OBJ_ARMOUR, ARM_CLOAK, 0, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 1, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_RATSKIN_CLOAK */
{
    "ratskin cloak", "ratskin cloak", NULL, NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +1, 0, ETC_BEOGH, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, -1, -1, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_GONG */
{
    "shield of the gong", "shield of the gong", NULL, NULL, 
    OBJ_ARMOUR, ARM_SHIELD, +18, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, -5, 0, 0, 0, 
        0, 0, 1, 0, 1, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _GONG_melee_effects, NULL, NULL, 
},

/* UNRAND_AIR */
{
    "amulet of the Air", "amulet of the Air", NULL, NULL, 
    OBJ_JEWELLERY, AMU_INACCURACY, 0, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 5, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SHADOWS */
{
    "ring of Shadows", "ring of Shadows", NULL, "Umbra", 
    OBJ_JEWELLERY, RING_INVISIBILITY, 0, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _SHADOWS_equip, _SHADOWS_unequip, NULL, NULL, NULL, NULL, 
},

/* UNRAND_CEKUGOB */
{
    "amulet of Cekugob", "amulet of Cekugob", NULL, NULL, 
    OBJ_JEWELLERY, AMU_WARDING, 0, 0, ETC_SILVER, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 1, 1, 0, 0, 0, 
        0, 0, 1, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FOUR_WINDS */
{
    "amulet of the Four Winds", "amulet of the Four Winds", NULL, NULL, 
    OBJ_JEWELLERY, AMU_CLARITY, 0, 0, ETC_POISON, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BLOODLUST */
{
    "necklace of Bloodlust", "necklace of Bloodlust", NULL, NULL, 
    OBJ_JEWELLERY, AMU_RAGE, 0, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 2, -2, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 9, 0, 
        0, 0, 3, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SHAOLIN */
{
    "ring of Shaolin", "ring of Shaolin", NULL, NULL, 
    OBJ_JEWELLERY, RING_EVASION, +8, 0, ETC_POISON, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_ROBUSTNESS */
{
    "ring of Robustness", "ring of Robustness", NULL, NULL, 
    OBJ_JEWELLERY, RING_PROTECTION, +8, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_MAGE */
{
    "ring of the Mage", "ring of the Mage", NULL, NULL, 
    OBJ_JEWELLERY, RING_WIZARDRY, 0, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SHIELDING */
{
    "brooch of Shielding", "brooch of Shielding", NULL, NULL, 
    OBJ_JEWELLERY, AMU_WARDING, 0, 0, ETC_MAGIC, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 4, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_RCLOUDS */
{
    "robe of Clouds", "robe of Clouds", NULL, NULL, 
    OBJ_ARMOUR, ARM_ROBE, +3, 0, ETC_MIST, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _RCLOUDS_equip, NULL, _RCLOUDS_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_PONDERING */
{
    "hat of Pondering", "hat of Pondering", NULL, NULL, 
    OBJ_ARMOUR, ARM_HAT, +3, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, +5, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, +10, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DEMON_AXE */
{
    "obsidian axe", "obsidian axe", NULL, NULL, 
    OBJ_WEAPONS, WPN_BROAD_AXE, +14, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_UNHOLY, 
    {
        SPWPN_VORPAL, 0, 0, +3, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, _DEMON_AXE_unequip, _DEMON_AXE_world_reacts, _DEMON_AXE_melee_effects, NULL, NULL, 
},

/* UNRAND_LIGHTNING_SCALES */
{
    "lightning scales", "lightning scales", NULL, NULL, 
    OBJ_ARMOUR, ARM_NAGA_BARDING, +6, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_RUNNING, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_BLACK_KNIGHT_HORSE */
{
    "Black Knight's horse barding", "Black Knight's horse barding", NULL, NULL, 
    OBJ_ARMOUR, ARM_CENTAUR_BARDING, +10, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_EVIL, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, _BLACK_KNIGHT_HORSE_world_reacts, NULL, NULL, NULL, 
},

/* UNRAND_VITALITY */
{
    "amulet of Vitality", "amulet of Vitality", NULL, NULL, 
    OBJ_JEWELLERY, AMU_REGENERATION, 0, 0, ETC_MUTAGENIC, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, +15, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_AUTUMN_KATANA */
{
    "autumn katana", "autumn katana", "katana", NULL, 
    OBJ_WEAPONS, WPN_LONG_SWORD, +8, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        -2, 0, 1, +2, +4, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DEVASTATOR */
{
    "shillelagh \"Devastator\"", "shillelagh \"Devastator\"", "shillelagh", "shatter", 
    OBJ_WEAPONS, WPN_CLUB, +6, 0, WHITE, 0, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +3, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _DEVASTATOR_equip, NULL, NULL, _DEVASTATOR_melee_effects, NULL, NULL, 
},

/* UNRAND_DRAGONSKIN */
{
    "dragonskin cloak", "opalescent scaly cloak", NULL, NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +4, 0, ETC_HEAL, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _DRAGONSKIN_equip, _DRAGONSKIN_unequip, NULL, NULL, NULL, NULL, 
},

/* UNRAND_OCTOPUS_KING_RING */
{
    "ring of the Octopus King", "ring of the Octopus King", NULL, NULL, 
    OBJ_JEWELLERY, RING_LOUDNESS, 0, 0, ETC_WATER, 0, 
    UNRAND_FLAG_UNIDED, 
    {
        0, 1, 1, 1, 1, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_WOE */
{
    "Axe of Woe", "Axe of Woe", NULL, NULL, 
    OBJ_WEAPONS, WPN_EXECUTIONERS_AXE, 0, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _WOE_melee_effects, NULL, NULL, 
},

/* UNRAND_MOON_TROLL_LEATHER_ARMOUR */
{
    "moon troll leather armour", "moon troll leather armour", NULL, NULL, 
    OBJ_ARMOUR, ARM_TROLL_LEATHER_ARMOUR, +4, 0, ETC_SHIMMER_BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_SPIRIT_SHIELD, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, +5, 
        0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_FINGER_AMULET */
{
    "macabre finger necklace", "macabre finger necklace", NULL, NULL, 
    OBJ_JEWELLERY, AMU_WARDING, 0, 0, ETC_BONE, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_SPIDER */
{
    "boots of the spider", "boots of the spider", NULL, NULL, 
    OBJ_ARMOUR, ARM_BOOTS, +3, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_JUMPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DARK_MAUL */
{
    "dark maul", "dark maul", "maul", NULL, 
    OBJ_WEAPONS, WPN_GREAT_MACE, +10, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +13, 0, 0, +2, +35, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_HIGH_COUNCIL */
{
    "hat of the High Council", "hat of the High Council", NULL, "Wiz-", 
    OBJ_ARMOUR, ARM_HAT, +2, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_ARCHMAGI, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_ARC_BLADE */
{
    "arc blade", "arc blade", NULL, "discharge,", 
    OBJ_WEAPONS, WPN_RAPIER, +4, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _ARC_BLADE_equip, _ARC_BLADE_unequip, NULL, _ARC_BLADE_melee_effects, NULL, NULL, 
},

/* UNRAND_SPELLBINDER */
{
    "demon whip \"Spellbinder\"", "demon whip \"Spellbinder\"", NULL, NULL, 
    OBJ_WEAPONS, WPN_DEMON_WHIP, +5, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ANTIMAGIC, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, _SPELLBINDER_melee_effects, NULL, NULL, 
},

/* UNRAND_ORDER */
{
    "lajatang of Order", "lajatang of Order", NULL, "silver,", 
    OBJ_WEAPONS, WPN_LAJATANG, +7, 0, ETC_SILVER, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 
        
    },
    NULL, NULL, NULL, _ORDER_melee_effects, NULL, NULL, 
},

/* UNRAND_FIRESTARTER */
{
    "great mace \"Firestarter\"", "great mace \"Firestarter\"", NULL, "inner flame,", 
    OBJ_WEAPONS, WPN_GREAT_MACE, +7, 0, RED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        2, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _FIRESTARTER_equip, _FIRESTARTER_unequip, NULL, _FIRESTARTER_melee_effects, NULL, NULL, 
},

/* UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR */
{
    "orange crystal plate armour", "orange crystal plate armour", NULL, NULL, 
    OBJ_ARMOUR, ARM_CRYSTAL_PLATE_ARMOUR, 8, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_ARCHMAGI, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_MAJIN */
{
    "Majin-Bo", "Majin-Bo", NULL, "Archmagi", 
    OBJ_WEAPONS, WPN_QUARTERSTAFF, +6, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_UNHOLY, 
    {
        SPWPN_VAMPIRISM, 0, 0, 0, 6, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 6, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    _MAJIN_equip, _MAJIN_unequip, NULL, NULL, NULL, NULL, 
},

/* UNRAND_GYRE */
{
    "quick blades \"Gyre\" and \"Gimble\"", "quick blades \"Gyre\" and \"Gimble\"", "quick blades", NULL, 
    OBJ_WEAPONS, WPN_QUICK_BLADE, 5, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, -3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

/* UNRAND_DUMMY2 */
{
    "DUMMY UNRANDART 2", "DUMMY UNRANDART 2", NULL, NULL, 
    OBJ_UNASSIGNED, 250, 250, 0, BLACK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 
        
    },
    NULL, NULL, NULL, NULL, NULL, NULL, 
},

#endif /* art_data_h */
